# Generated by Django 3.1.3 on 2020-11-19 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DrPhoneNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.IntegerField(max_length=12)),
                ('number_of_message_sent', models.IntegerField(max_length=10)),
                ('have_whatsapp', models.BooleanField()),
                ('note', models.CharField(max_length=200)),
                ('date_of_sent', models.DateTimeField(verbose_name='date of sent')),
            ],
        ),
    ]
