# Generated by Django 3.1.3 on 2020-11-19 22:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drphonenumber',
            name='id',
        ),
        migrations.AlterField(
            model_name='drphonenumber',
            name='phone_number',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^\\d{0,10}$')]),
        ),
    ]
