# Generated by Django 3.1.3 on 2020-11-19 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0002_auto_20201120_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drphonenumber',
            name='date_of_sent',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='drphonenumber',
            name='number_of_message_sent',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='drphonenumber',
            name='phone_number',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
    ]
