# Generated by Django 3.1.3 on 2020-11-20 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0003_auto_20201120_0020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drphonenumber',
            name='date_of_sent',
        ),
        migrations.AlterField(
            model_name='drphonenumber',
            name='number_of_message_sent',
            field=models.IntegerField(default=0),
        ),
    ]
