# Generated by Django 3.1.3 on 2020-11-22 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0004_auto_20201120_0234'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_index_sent', models.IntegerField()),
                ('last_date_of_sent', models.DateTimeField()),
            ],
        ),
    ]
