# Generated by Django 3.1.3 on 2020-11-22 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0006_auto_20201122_0344'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsetting',
            name='last_phone_number',
            field=models.CharField(default='0', max_length=15),
        ),
    ]
